apiVersion: v1
kind: Pod

metadata:
  name: web-server-pod

spec:
  containers:
    - name: web-server-container
      image: my-web-server
      ports:
        - containerPort: 80
      imagePullPolicy: IfNotPresent

